name: Generate Live Leboncoin API

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm init -y
          npm install leboncoin-api-search
          sed -i 's/"type": "commonjs"//"type": "module"/' package.json

      - name: Run Scraper
        run: node index.js

      - name: Deploy API to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: gh-pages
